runtime: nodejs16

env_variables:
  CLOUD_SQL_USERNAME: db_admin
  CLOUD_SQL_PASSWORD: 12345678ab
  CLOUD_SQL_DATABASE_NAME: test_deploy_scg
  CLOUD_SQL_CONNECTION_NAME: /cloudsql/testdeploy-330007:asia-southeast1:test-deploy  
  CLOUD_SQL_CONNECTION_HOST: localhost
  
beta_settings:
  cloud_sql_instances: testdeploy-330007:asia-southeast1:test-deploy=tcp:5500

